package ma.newdev.rh.entity;

public enum TypeNotification {
    LEAVE_SUBMITTED,
    LEAVE_APPROVED,
    LEAVE_REFUSED,
    EVALUATION_SUBMITTED,
    ASSET_ASSIGNED,
    ASSET_RETURNED,
    PROFILE_CHANGE_SUBMITTED,
    PROFILE_CHANGE_APPROVED,
    PROFILE_CHANGE_REJECTED,
    PAYSLIP_GENERATED,
    PASSWORD_CHANGED,
    ANNOUNCEMENT
}
